#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y

#Layer LED config -------------------
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=n

#ZMK studio -------------------
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_POINTING=y
